create table models
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

alter table models
    owner to core;

create table versions
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6)
);

alter table versions
    owner to core;

create table questions
(
    id           bigint generated by default as identity
        primary key,
    question_key bigint,
    text         text,
    version_id   bigint
        references versions
);

alter table questions
    owner to core;

create table answers
(
    id          bigint generated by default as identity
        primary key,
    answer_key  bigint,
    text        text,
    model_id    bigint references models,
    question_id bigint references questions
);

alter table answers
    owner to core;

create table hef_users
(
    id                  bigint generated by default as identity
        primary key,
    username            varchar(255),
    next_question_id    bigint references questions,
    current_question_id bigint references questions
);

alter table hef_users
    owner to core;

create table evaluations
(
    id                      bigint generated by default as identity
        primary key,
    comment                 varchar(10000),
    accuracy                double precision,
    comprehensiveness       double precision,
    clarity                 double precision,
    empathy                 double precision,
    bias                    double precision,
    harm                    double precision,
    understanding           double precision,
    relevance               double precision,
    currency                double precision,
    reasoning               double precision,
    factuality_verification double precision,
    answer_id               bigint references answers,
    question_id             bigint references questions,
    user_id                 bigint references hef_users
);

alter table evaluations
    owner to core;

create unique index answers_question_id_model_id on answers (question_id, model_id);
create unique index evaluations_answer_id_user_id on evaluations (answer_id, user_id);
create index evaluations_question_id_user_id on evaluations (question_id, user_id);
create unique index models_name on models (name);
create unique index questions_question_key on questions (question_key);
create unique index hef_users_username on hef_users (username);